---

- name: gomax integration rollback
  hosts: gazellacom
  become: true
  roles:
    - role: gazellacom-rollback
      gazellacom_mode: listbuild                 # rollback, listbuild, listbuildurl, mixed
      gacellacom_limit: 10
      gazellacom_remote_workdir: '/opt/deployment-awx'
