---

gazellacom_build_workspace: '/opt/workspace'
gazellacom_build_workdir: "{{ gazellacom_build_workspace }}/{{  gazellacom_project }}/{{ gazellacom_project }}-deploy-{{ gazellacom_environment }}"
gazellacom_build_sequence: "{{ gazellacom_build_workspace }}/{{  gazellacom_project }}/{{ gazellacom_project }}-sequence-{{ gazellacom_environment }}"
gazellacom_build_sequence_file: "{{ gazellacom_build_sequence }}/sequence.ini"
gazellacom_build_user: gazellacom_build
gazellacom_build_group: "{{ gazellacom_build_user }}"
gazellacom_remote_workdir: '/opt/deployments-awx'
gazellacom_build_profile_customer: null
gazellacom_build_profile_environment: integration

gazellacom_builder_host: localhost
gazellacom_build_app: true
gazellacom_build_delete_workdir: false
gazellacom_build_shell_interpreter: /bin/bash
gazellacom_build_relative_path_to_deploy_dir: target/gazellacom/
gazellacom_java_package_version: 'java-17-openjdk'
gazellacom_java_home: '/usr/lib/jvm/'

gazellacom_app_workdir: '/tmp/workdir'
gazellacom_app_user: gazellacom_app
gazellacom_app_group: "{{ gazellacom_app_user }}"

gazellacom_app_service_name: "{{ app_name }}"
gazellacom_deploy_systemd_service_conf: "/etc/{{ app_name }}.conf"
gazellacom_app_validation_host: localhost
gazellacom_systemd_service_template: 'templates/service_systemd.j2'
gazellacom_systemd_home: '/usr/lib/systemd/system'

gazellacom_app_port: 8080
gazellacom_app_port_firewalld: "{{ gazellacom_app_port }}"
gazellacom_app_firewalld_enabled: false
gazellacom_firewalld_package: firewalld

