---

#- name: "Define path to mvnw script."
#  ansible.builtin.set_fact:
#    path_to_mvnw: "{{ gazellacom_build_workdir }}/{{ gazellacom_build_source_folder | default('') }}/mvnw"

- name: "Build app from {{ gazellacom_build_repo_url }} on '{{ gazellacom_builder_repo_branch }}'."
  block:

    - name: "Increment variable gazellacom_number_build = {{ gazellacom_number_build | int + 1 }}"
      set_fact: gazellacom_number_build={{ gazellacom_number_build | int + 1 }}

    - name: "set sequence file {{ gazellacom_build_sequence_file }} to {{ gazellacom_number_build }}"
      ansible.builtin.shell: "echo {{ gazellacom_number_build }} > {{ gazellacom_build_sequence_file }}"

    - name: "Delete previous workdir {{ gazellacom_build_workdir }}."
      ansible.builtin.file:
        path: "{{ gazellacom_build_workdir }}"
        state: absent

    - name: "Ensure app sequences exists: {{ gazellacom_build_sequence }}"
      ansible.builtin.file:
        path: "{{ gazellacom_build_sequence }}"
        state: directory
        owner: "{{ gazellacom_build_user }}"
        group: "{{ gazellacom_build_group }}"
        mode: 0775
        force: yes

    - name: "Ensure app workdir exists: {{ gazellacom_build_workdir }}"
      ansible.builtin.file:
        path: "{{ gazellacom_build_workdir }}"
        state: directory
        owner: "{{ gazellacom_build_user }}"
        group: "{{ gazellacom_build_group }}"
        mode: 0775
        force: yes

    - name: "Checkout the application source code Gazella COM"
#      become: yes
      ansible.builtin.git:
        repo: "{{ gazellacom_build_repo_url }}"
        dest: "{{ gazellacom_build_workdir }}"
        version: "{{ gazellacom_build_repo_branch }}"
      ignore_errors: yes  

    - name: "Bitbucket Recursively change ownership"
      become: yes
      file:
        path: "{{ gazellacom_build_workdir}}"
        state: directory
        recurse: yes
        owner: "{{ gazellacom_build_user }}"
        group: "{{ gazellacom_build_group }}"

    - name: "Git fix trusted directory"
      ansible.builtin.command: "git config --global --add safe.directory {{ gazellacom_build_workdir }}"
      args:
        chdir: "{{ gazellacom_build_workdir }}"

    - name: "Build the App using Maven"
      ansible.builtin.command: "mvn -X -s customer/{{ gazellacom_build_profile_customer }}/settings.xml clean package -Dbuild.number={{ gazellacom_number_build }} -P{{ gazellacom_build_profile_environment }}"
      register: mvn_build
      environment:
        JAVA_HOME: "{{ gazellacom_java_home }}"
      args:
        chdir: "{{ gazellacom_build_workdir }}"
      changed_when: false

    - name: "Display build application log"
      ansible.builtin.debug:
        var: mvn_build.stdout
#      when:
#        - display_mvn_output is defined
