---
  
- name: "list  from rollback ."
  block:

    - name: "List to  rollback build "
      become: yes
      ansible.builtin.shell: "ls {{ gazellacom_remote_workdir }} | sort -k {{ gacellacom_limit }} "
      register: gazellacom_list_build_read

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: gazellacom_list_build_read.stdout_lines
        verbosity: 2
