---

- name: "Deploy new package on wildfly"
  ansible.builtin.include_tasks: rollback.yml
  when: gazellacom_mode == 'rollback'    

- name: "List of deploy package build"
  ansible.builtin.include_tasks: listdeploy.yml
  when: gazellacom_mode == 'listbuild'
